steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/what-should-i-eat-412918/wsie', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/what-should-i-eat-412918/wsie']

# Optionally, specify substitutions for variables in your build steps
substitutions:
  _PROJECT_ID: what-should-i-eat-412918
