version: '3'
services:
  client:
    build: './client'
    ports:
      - "3000:3000"
  server:
    build: './server'
    ports:
      - "3001:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/WSIE
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - mongodb_data:/data/db
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./client/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

volumes:
  mongodb_data:
